//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModMonitor.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.1.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ShowPower {
            get {
                return ((bool)(this["ShowPower"]));
            }
            set {
                this["ShowPower"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ShowPowerSetpoint {
            get {
                return ((bool)(this["ShowPowerSetpoint"]));
            }
            set {
                this["ShowPowerSetpoint"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ShowTemperature {
            get {
                return ((bool)(this["ShowTemperature"]));
            }
            set {
                this["ShowTemperature"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ShowTemperatureSetpoint {
            get {
                return ((bool)(this["ShowTemperatureSetpoint"]));
            }
            set {
                this["ShowTemperatureSetpoint"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ShowVoltage {
            get {
                return ((bool)(this["ShowVoltage"]));
            }
            set {
                this["ShowVoltage"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ShowCurrent {
            get {
                return ((bool)(this["ShowCurrent"]));
            }
            set {
                this["ShowCurrent"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ShowLiveResistance {
            get {
                return ((bool)(this["ShowLiveResistance"]));
            }
            set {
                this["ShowLiveResistance"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ShowColdResistance {
            get {
                return ((bool)(this["ShowColdResistance"]));
            }
            set {
                this["ShowColdResistance"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ShowBatteryVoltage {
            get {
                return ((bool)(this["ShowBatteryVoltage"]));
            }
            set {
                this["ShowBatteryVoltage"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ShowBoardTemperature {
            get {
                return ((bool)(this["ShowBoardTemperature"]));
            }
            set {
                this["ShowBoardTemperature"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ShowRoomTemperature {
            get {
                return ((bool)(this["ShowRoomTemperature"]));
            }
            set {
                this["ShowRoomTemperature"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Lime")]
        public global::System.Drawing.Color ColorPower {
            get {
                return ((global::System.Drawing.Color)(this["ColorPower"]));
            }
            set {
                this["ColorPower"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Green")]
        public global::System.Drawing.Color ColorPowerSetpoint {
            get {
                return ((global::System.Drawing.Color)(this["ColorPowerSetpoint"]));
            }
            set {
                this["ColorPowerSetpoint"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Red")]
        public global::System.Drawing.Color ColorTemperature {
            get {
                return ((global::System.Drawing.Color)(this["ColorTemperature"]));
            }
            set {
                this["ColorTemperature"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("DarkRed")]
        public global::System.Drawing.Color ColorTemperatureSetpoint {
            get {
                return ((global::System.Drawing.Color)(this["ColorTemperatureSetpoint"]));
            }
            set {
                this["ColorTemperatureSetpoint"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Cyan")]
        public global::System.Drawing.Color ColorVoltage {
            get {
                return ((global::System.Drawing.Color)(this["ColorVoltage"]));
            }
            set {
                this["ColorVoltage"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Goldenrod")]
        public global::System.Drawing.Color ColorCurrent {
            get {
                return ((global::System.Drawing.Color)(this["ColorCurrent"]));
            }
            set {
                this["ColorCurrent"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("MediumPurple")]
        public global::System.Drawing.Color ColorLiveResistance {
            get {
                return ((global::System.Drawing.Color)(this["ColorLiveResistance"]));
            }
            set {
                this["ColorLiveResistance"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Purple")]
        public global::System.Drawing.Color ColorColdResistance {
            get {
                return ((global::System.Drawing.Color)(this["ColorColdResistance"]));
            }
            set {
                this["ColorColdResistance"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Black")]
        public global::System.Drawing.Color ColorBatteryVoltage {
            get {
                return ((global::System.Drawing.Color)(this["ColorBatteryVoltage"]));
            }
            set {
                this["ColorBatteryVoltage"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("DarkSalmon")]
        public global::System.Drawing.Color ColorBoardTemperature {
            get {
                return ((global::System.Drawing.Color)(this["ColorBoardTemperature"]));
            }
            set {
                this["ColorBoardTemperature"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("BurlyWood")]
        public global::System.Drawing.Color ColorRoomTemperature {
            get {
                return ((global::System.Drawing.Color)(this["ColorRoomTemperature"]));
            }
            set {
                this["ColorRoomTemperature"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("F")]
        public global::LibDnaSerial.TemperatureUnit TemperatureUnit {
            get {
                return ((global::LibDnaSerial.TemperatureUnit)(this["TemperatureUnit"]));
            }
            set {
                this["TemperatureUnit"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool TemperatureUnitForce {
            get {
                return ((bool)(this["TemperatureUnitForce"]));
            }
            set {
                this["TemperatureUnitForce"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("50")]
        public long SampleThrottle {
            get {
                return ((long)(this["SampleThrottle"]));
            }
            set {
                this["SampleThrottle"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ExpandGraph {
            get {
                return ((bool)(this["ExpandGraph"]));
            }
            set {
                this["ExpandGraph"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool AutoDownloadStats {
            get {
                return ((bool)(this["AutoDownloadStats"]));
            }
            set {
                this["AutoDownloadStats"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("3")]
        public float FireDuration {
            get {
                return ((float)(this["FireDuration"]));
            }
            set {
                this["FireDuration"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Red")]
        public global::System.Drawing.Color GraphColorTemperature {
            get {
                return ((global::System.Drawing.Color)(this["GraphColorTemperature"]));
            }
            set {
                this["GraphColorTemperature"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Green")]
        public global::System.Drawing.Color GraphColorPower {
            get {
                return ((global::System.Drawing.Color)(this["GraphColorPower"]));
            }
            set {
                this["GraphColorPower"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Blue")]
        public global::System.Drawing.Color GraphColorVoltage {
            get {
                return ((global::System.Drawing.Color)(this["GraphColorVoltage"]));
            }
            set {
                this["GraphColorVoltage"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Orange")]
        public global::System.Drawing.Color GraphColorCurrent {
            get {
                return ((global::System.Drawing.Color)(this["GraphColorCurrent"]));
            }
            set {
                this["GraphColorCurrent"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Gray")]
        public global::System.Drawing.Color GraphColorPercentage {
            get {
                return ((global::System.Drawing.Color)(this["GraphColorPercentage"]));
            }
            set {
                this["GraphColorPercentage"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool GraphShowGridLines {
            get {
                return ((bool)(this["GraphShowGridLines"]));
            }
            set {
                this["GraphShowGridLines"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Gray")]
        public global::System.Drawing.Color ColorBatteryLevel {
            get {
                return ((global::System.Drawing.Color)(this["ColorBatteryLevel"]));
            }
            set {
                this["ColorBatteryLevel"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ShowBatteryLevel {
            get {
                return ((bool)(this["ShowBatteryLevel"]));
            }
            set {
                this["ShowBatteryLevel"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Purple")]
        public global::System.Drawing.Color GraphColorResistance {
            get {
                return ((global::System.Drawing.Color)(this["GraphColorResistance"]));
            }
            set {
                this["GraphColorResistance"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool AutoConnect {
            get {
                return ((bool)(this["AutoConnect"]));
            }
            set {
                this["AutoConnect"] = value;
            }
        }
    }
}
